// Living town: walkable interiors, NPCs and simple walking animation.
(function(){
 const oldMove=window.move,oldAction=window.action,oldDrawHero=window.drawHero;
 let step=0;
 const interiors={home:{name:'民家',npc:'老人',line:'洞窟のさらに向こうには、昔の街道が続いておるそうじゃ。'},weapon:{name:'武器屋',npc:'鍛冶屋',line:'剣は手入れが命だ。いい武器なら旅がずっと楽になるぞ。'},armor:{name:'防具屋',npc:'職人',line:'防具は命を守る最後の砦。軽く見るんじゃないよ。'},item:{name:'道具屋',npc:'店員',line:'薬草や旅の道具を揃えているよ。品物はもうすぐ入荷予定！'},inn:{name:'宿屋',npc:'女将',line:'旅人さん、疲れた顔してるね。ゆっくりしておいき。'}};
 const doors={home:[2,3],weapon:[7,3],armor:[12,3],item:[3,9],inn:[11,9]};
 function hero(x,y){oldDrawHero(x,y);const X=x*TILE,Y=y*TILE;if(step%2){ctx.fillStyle='#f0c25b';ctx.fillRect(X+8,Y+29,5,3);ctx.fillRect(X+30,Y+27,4,3)}}
 window.drawHero=hero;
 function drawNPC(x,y,type){const X=x*TILE,Y=y*TILE;ctx.fillStyle='rgba(0,0,0,.25)';ctx.fillRect(X+10,Y+32,20,4);ctx.fillStyle=type==='inn'?'#9b3157':type==='weapon'?'#7b3f20':'#3f6b48';ctx.fillRect(X+11,Y+16,18,17);ctx.fillStyle='#edbd8d';ctx.fillRect(X+13,Y+7,15,11);ctx.fillStyle='#4a2d20';ctx.fillRect(X+11,Y+5,19,5);ctx.fillStyle='#1d1d24';ctx.fillRect(X+16,Y+12,2,2);ctx.fillRect(X+24,Y+12,2,2)}
 function drawInterior(){const type=state.interiorType||'home';for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const X=x*TILE,Y=y*TILE;ctx.fillStyle=(x===0||y===0||x===15||y===11)?'#4b3426':'#9b6a3f';ctx.fillRect(X,Y,40,40);if(x>0&&y>0&&x<15&&y<11){ctx.fillStyle='#a97848';ctx.fillRect(X+2,Y+2,36,36);ctx.strokeStyle='rgba(70,40,20,.25)';ctx.strokeRect(X+2,Y+2,36,36)}}ctx.fillStyle='#5c351f';ctx.fillRect(2*TILE,2*TILE,12*TILE,2*TILE);ctx.fillStyle='#c09054';ctx.fillRect(2*TILE,2*TILE+4,12*TILE,8);for(let x=3;x<13;x+=2){ctx.fillStyle='#51311f';ctx.fillRect(x*TILE,3*TILE,25,30);ctx.fillStyle='#d9b56d';ctx.fillRect(x*TILE+4,3*TILE+5,17,5)}if(type==='inn'){ctx.fillStyle='#eee0bd';ctx.fillRect(2*TILE,7*TILE,90,55);ctx.fillRect(11*TILE,7*TILE,90,55);ctx.fillStyle='#7f3149';ctx.fillRect(2*TILE,7*TILE,90,10);ctx.fillRect(11*TILE,7*TILE,90,10)}if(type==='weapon'||type==='armor'){for(let i=0;i<4;i++){ctx.fillStyle='#c8d0d8';ctx.fillRect((4+i*2)*TILE,5*TILE,5,24);ctx.fillStyle='#d5a73a';ctx.fillRect((4+i*2)*TILE-5,5*TILE+19,15,4)}}if(type==='item'){for(let i=0;i<5;i++){ctx.fillStyle=['#5cb85c','#c24c4c','#4c79c2','#c2974c','#8a5bb8'][i];ctx.beginPath();ctx.arc((4+i*2)*TILE,5*TILE+20,8,0,Math.PI*2);ctx.fill()}}drawNPC(8,4,type);ctx.fillStyle='#51311f';ctx.fillRect(7*TILE,10*TILE+10,80,25);ctx.fillStyle='#e0bd73';ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillText('EXIT',8*TILE,10*TILE+27);hero(state.interiorX||8,state.interiorY||9)}
 function findDoor(){return Object.entries(doors).find(([,p])=>p[0]===state.townX&&p[1]===state.townY)?.[0]}
 function enter(type){state.area='interior';state.interiorType=type;state.interiorX=8;state.interiorY=9;state.inMenu=false;closeOverlay();drawInterior();say(`${interiors[type].name}の中。木の床にランプの明かりが揺れている。`)}
 function moveInterior(dx,dy){const nx=state.interiorX+dx,ny=state.interiorY+dy;if(nx<1||nx>14||ny<4||ny>10){say('そこには進めない。');return}if(nx===8&&ny===4){say(`${interiors[state.interiorType].npc}がいる。「しらべる」で話せる。`);return}state.interiorX=nx;state.interiorY=ny;step++;drawInterior();if(ny===10&&(nx===7||nx===8)){state.area='town';state.townX=doors[state.interiorType][0];state.townY=doors[state.interiorType][1];drawTown();say(`${interiors[state.interiorType].name}を出た。`)}}
 window.move=function(dx,dy){if(state.inBattle||state.inMenu)return;if(state.area==='interior'){moveInterior(dx,dy);return}step++;oldMove(dx,dy)};
 window.action=function(){if(state.inBattle||state.inMenu)return;if(state.area==='town'){const d=findDoor();if(d){enter(d);return}}if(state.area==='interior'){const near=Math.abs((state.interiorX||8)-8)+Math.abs((state.interiorY||9)-4)<=2;if(near){const i=interiors[state.interiorType];say(`${i.npc}「${i.line}」`);if(state.interiorType==='inn'){state.hp=state.maxHp;state.mp=state.maxMp;updateUI()}return}say('部屋を見回した。旅人の暮らしを感じる。');return}oldAction()};
 const oldCurrent=window.drawCurrent;window.drawCurrent=function(){if(state.area==='interior')drawInterior();else oldCurrent()};
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({up:()=>move(0,-1),down:()=>move(0,1),left:()=>move(-1,0),right:()=>move(1,0)})[b.dataset.action]());document.getElementById('action').onclick=()=>action();window.onkeydown=e=>{const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))move(0,-1);if(['arrowdown','s'].includes(k))move(0,1);if(['arrowleft','a'].includes(k))move(-1,0);if(['arrowright','d'].includes(k))move(1,0)};
 if(state.area==='interior')drawInterior();
})();